name: simsocial
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  intl: ^0.17.0
 
  
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.3.4+2
  flutter_facebook_sdk: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_profile_picture: ^2.0.0
  uuid: ^3.0.6
  splashscreen: ^1.3.5
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - fonts/
  fonts: 
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-Bold.ttf